### ISSUE TITLE
Prohibit calling a super method from a method other than its overridden method

### ISSUE THREAD

**Issue by jzbrooks** [Faithlife/AndroidLint#6]
Calling super methods that have side effects (like many android lifecycle methods) multiple times can lead to hard to track down bugs. 

```
 Caused by: java.lang.IllegalStateException: SavedStateRegistry was already restored.
    at androidx.savedstate.SavedStateRegistry.performRestore(SavedStateRegistry.java:191)
    at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.java:62)
    at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:321)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
```

Usually it is a good idea to only explicitly call a super method from a method overriding that method. e.g.

```java
	@Override
	protected void onCreate(Bundle savedInstanceState)
	{
	        super.onCreate(savedInstanceState);
	        // ...
	}
```

And avoid calling it transitively, like

```java
	@Override
	protected void onCreate(Bundle savedInstanceState)
	{
	        setTheme();
	        // ...
	}

        private void setTheme() {
                super.onCreate(savedInstanceState);
        }
```

**Comment by jzbrooks** [comment]
Would be similar to https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/WrongCallDetector.java

**Comment by jzbrooks** [comment]
For performance reasons it may be prudent to limit the detector to method calls with known side effects like `Activity.onCreate`.

It seems like a good idea generally, though, if performance isn't an issue.
